spring:
  datasource:
    url: jdbc:postgresql://dpg-cpc4imkf7o1s7389t8ig-a/spring_project_9c2k
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
rsa:
  private-key: file:/etc/secrets/private.pem
  public-key: file:/etc/secrets/public.pem